### ISSUE TITLE
Script Error: Template reference cannot use templates (Decor_sealed_storage) when trying to build a Doom 2 mapset.

### ISSUE THREAD

**Issue by BoneofMalkav** [caligari87/ObAddon#112]
Trying to build a Doom 2 mapset with this recent dev build of ObAddon (From 5 hours ago, 1/24/2021) and keeps generating that error. With the settings I have set in the attached log file I'm not sure what I should disable for the time being.

[LOG.txt](https://github.com/caligari87/ObAddon/files/5863255/LOG.txt)

**Comment by GTD-Carthage** [comment]
Can't seem to replicate your issue - generation proceeds just fine and the specific item being pointed out by your log file doesn't seem to have any problem. Just in case, are you using a fresh installation of Oblige without any original files having been overwritten?

The log file also suggests you were using an outdated CONFIG - I doubt this could have been related, but re-saving your CONFIG file should at least remove this warning from the log.

**Comment by BoneofMalkav** [comment]
Version 7.70 oblige (with Oblige64 executable) if that's what your asking but previous versions of ObAddon (Both Beta and full releases) rarely had an issue before. I would say I probably assembled the ObAddonBeta pk3 incorrectly but that can't be cause I followed the instructions of the README.md to the letter for the manual build setup. (Adding the contents of the scr folder from the repo to a folder then brought those folders into the zip then renamed to pk3)
> 
> 
> Just in case, are you using a fresh installation of Oblige without any original files having been overwritten?

**Comment by GTD-Carthage** [comment]
For clarification, you are supposed to zip the contents of the /src/ folder as-is, rather than placing it into another folder and zipping that folder if I'm reading this correctly. The immediate top level contents of your pk3 archive should be the `data`, `games`, `modules`, and `scripts` folders.

**Comment by BoneofMalkav** [comment]
That is how I'm doing it. the pk3 is only data, games, modules,and scripts folders.

**Comment by GTD-Carthage** [comment]
Unfortunately, I still can't tell what's going on with your copy - one last resort is to run 'unpacked' by unzipping the contents of the `src` folder directly into your Oblige directory and overwriting all existing files. I recommend doing this on a fresh download of Oblige. The issue your log file ends with pertains to something that's simply not there and I've triple-checked this part.

**Comment by BoneofMalkav** [comment]
A complete reinstall of Oblige solved it. Sorry for the inconvenience.

**Comment by GTD-Carthage** [comment]
No problem. Enjoy your levels! I'll close this issue for now.
