### ISSUE TITLE
Unknown class name 'Motherdemon' of type 'Object'

### ISSUE THREAD

**Issue by alphatonic** [caligari87/ObAddon#129]
Script error, "WADNAME.wad:ZSCRIPT" line 48:
Unknown class name 'Motherdemon' of type 'Object'

Any way to fix this?!

**Comment by GTD-Carthage** [comment]
This doesn't look like an ObAddon/Oblige issue - have you ensured your mods are not conflicting and work on the appropriate sourceport?

**Comment by alphatonic** [comment]
Yeah the config I am using works with the standard doom.wad it only breaks when i use oblige wads.

EDIT: I figured it out. The Project Brutality 3.0 version i was using is the culprit, sorry for wasting your time. I downgraded to an older version and it loads the oblige.wads. Awesome work you do with the ObAddon BTW.
