### ISSUE TITLE
"Subways" variant of street mode

### ISSUE THREAD

**Issue by caligari87** [caligari87/ObAddon#15]
Requested by `roguelike2018#2931` on Discord. He has offered to provide prefabs/templates and textures if needed. 

* Would need specialized or chained joiners (stairs!) for going deep underground. 
* Ideally tunnels would be long one-way (non-bending) indoor "streets" with caps on the ends (like fallen ceilings or close-off barriers)
* Metro-style big doors would be cool to split long tunnels.
* Vistas and windows would need to be neutered or disabled somehow to properly give the impression of underground areas.
* Rooms branching off tunnels could have "station" joiner prefabs.
* Very few tunnel branches, unlike streets. Parallel tunnels are more appropriate.
* Probably straight tunnels only unless gentle curves are feasible.
* Use variant of sidewalk code to generate continuous rails?

**Comment by Armaetus** [comment]
I can see this as you said, an indoor variant of Streets Mode with some considerable modifications...And knowing how subways are, they're typically dark.

**Comment by Armaetus** [comment]
The user mentioned above left the Discord but we now have the Minecraft-like tunnels, does this kind of apply to this issue?

**Comment by GTD-Carthage** [comment]
I've decided to close the issue in as much as at least we've met the original user's demands halfway and that... the guy doesn't look like he's interested to come back and witness the changes anyway...
