### ISSUE TITLE
Proposal: Swamp terrain

### ISSUE THREAD

**Issue by BiggestC** [caligari87/ObAddon#16]
Suggestion to add swamp terrain that follows the general layout of the cavern terrain and always has an open roof.

Inspiration: The new fog generator and the Darkmere level from Hexen, as well as some of the levels from Metro: Last Light.

**Comment by GTD-Carthage** [comment]
I think this can go toe-to-toe with my planned improvements for parks now that I have something better in mind for it - specifically, I'm thinking of making a variation of parks where it has completely naturalistic walls. It should be very easy to do. :)

**Comment by Armaetus** [comment]
Have we done anything on this yet?

**Comment by GTD-Carthage** [comment]
I would like to say this has finally been superseded by the new upcoming Nature Mode and it would be up to the user to configure their generator in a fashion that can generate something more closely to a swamp than prior.
