### ISSUE TITLE
[Idea] Custom Thing Placement Addon Needed

### ISSUE THREAD

**Issue by mattbratt11** [caligari87/ObAddon#23]
I didn’t see an addon for ObAddon called “Custom Things”, where it has Monsters, Weapons, Items, etcetera, from Realm667 and/or other websites and/or projects such as Samsara and/or other compatibilities, including Doom RPG SE, Complex Clustermods, and all the other varieties whether mentioned or not, especially Cacoward contestants, Runners-Up and/or Winners. Sorry about confusion, but Custom Things Addon needs to be made as a Community for ObAddon. Previously, Custom Monsters was made for the old version of Oblige, but it needs improvements, compatibility, and an Update for ObAddon.
P.S. Also, please think about Glaice’s improvements previously present from Oblige.
Thanks and keep the community living long and prosper and doom on!

**Comment by GTD-Carthage** [comment]
If you've been using Glaice's Oblige 7.59 version, all additions from it are the working base for ObAddon. :) Glaice's custom textures from 6.20 have also made a come back as a the Epic Textures module for ObAddon plus a lot of new extra goodies with it (such as Epic Textures exclusive prefabs).

Custom things are something we hope to figure out in the future and we're definitely interested in adding stuff like new sprites and actors. (heck, we could even get Oblige to generate its own DECORATE/ACS/ZScript) for as long as we're all still doing it within the limits of the traditional Doom 2 binary map format. (no UDMF)

**Comment by GTD-Carthage** [comment]
I am closing this issue for now as baseline support for adding custom things is already there - now people really just need to make those said things.
