### ISSUE TITLE
[linux] where to install ObAddon ?

### ISSUE THREAD

**Issue by axredneck** [caligari87/ObAddon#24]
I tried to place it into $HOME/.oblige/addons but Oblige doesn't see it.

**Comment by caligari87** [comment]
Unless you re-compile Oblige to look in your home folder, it won't see it there. It needs to be in the `addons/` folder in the Oblige install directory. 

That said, on Linux there is an error with Oblige itself, where loading prefabs inside addons is broken. Not sure when or if this will be fixed. I'd recommend having a standalone Oblige folder and extracting the contents of the ObAddon pk3 into the directory (so the ObAddon `games/` subfolder overwrites the Oblige `games/` subfolder, etc).

**Comment by axredneck** [comment]
Thank You. So it would be better to use Windows version with Wine.
