### ISSUE TITLE
Crashing, running out of memory with large maps and wads

### ISSUE THREAD

**Issue by Epictyphlosion** [caligari87/ObAddon#25]
This has been bugging me a lot recently.

In the newest release, if you try to make a megawad with extreme size maps, OBLIGE always crashes (either around map 20-32 or when building the nodes) before completing the wad.

I made sure auto-detailing was turned on, and even when it is on, OBLIGE still crashes. Even if you set floor and wall detailing to "Rare," it still crashes, sometimes it actually generates an error if it crashes on the node building part, citing a lack of memory. (I have 8GB of RAM, and OBLIGE crashes when it uses up only 1.6-1.7GB)

What doesn't make sense is that OBLIGE generated megawads with extreme size maps perfectly fine in previous releases, but now it doesn't.

**Comment by Shydrad** [comment]
I was having that issue today too, I used the universal 4GB ram patcher from Nexus mods (oblivion one). It worked like a charm for 32 maps of **EXTREME**!
I don't know how anyone feels about links here, but here is the exact thing I used. Just target Oblige's exe file and hit patch. No more crashing at 2GB.

[https://www.nexusmods.com/oblivion/mods/45576?tab=files](https://www.nexusmods.com/oblivion/mods/45576?tab=files)
If links aren't allowed/welcome here, I do apologize.

Hope it helps, cheers!
