### ISSUE TITLE
ObAddon is useless during April 1st

### ISSUE THREAD

**Issue by axredneck** [caligari87/ObAddon#27]
There should be an option to turn off this "Trololo Mode"

**Comment by caligari87** [comment]
I see no reason to bother with a toggle for this. It's one day. If you absolutely *cannot* live without random maps for 24 hours, generate an extra megawad the night before.

EDIT: This being said, it looks like the offending code has been [formally removed anyway as of the latest release.](https://github.com/caligari87/ObAddon/releases/tag/2019-04-03)

**Comment by axredneck** [comment]
> It's one day.

It was first day i used ObAddon so initially i thought it's a bug.
