### ISSUE TITLE
[Idea] UDMF Format for ZDoom-related ports needed.

### ISSUE THREAD

**Issue by mattbratt11** [caligari87/ObAddon#33]
I was wondering if ObAddon can use UDMF Format to generate maps for ZDoom-related ports such as Zandronum and GZDoom.

Also, is there any chance you can bring all the actors of ScoreDoom’s Addon Packs into a single pk3 file (including Boss Chains), ready for ObAddon to place in maps?

If ScoreDoom has a Boss Chain, they had Barons, Cyberdemons and Spider Masterminds.
So if this is accepted, how about additional boss chains such as Arachnotrons and Mancubi?

This request is entirely optional, unless it’s approved. Keep up the good work.

**Comment by Armaetus** [comment]
Doing this would require changing every single WAD prefab over to UDMF format and I  don't even know if prBoom supports that format for those who want to play Oblige using non-ZDoom ports.

**Comment by caligari87** [comment]
The map input / output is handled on the C++ side of things, so that would require significant work on code that none of the team know anything about, plus recompiling and re-releasing a new version of Oblige itself rather than an addon. I don't see that happening.
