### ISSUE TITLE
[Idea] User made custom text screen intermissions.

### ISSUE THREAD

**Issue by REVonGit** [caligari87/ObAddon#39]
The idea is to allow map makers to set up custom text screens written by the user and enable them to set the text screens at the beginning of any level they want.

Example for menu format:

Text Screen 1:
______________________________ .
|Text Box for user to write in. |
|_____________________________|
Show on [MAP01]

Beginning O
End          O
+Add

**Comment by caligari87** [comment]
I'm going to vote no on this. Makes no sense to have custom story fields in a random map generator. Edit the .wad after generating it if you want a custom story.
