### ISSUE TITLE
Chainsaw

### ISSUE THREAD

**Issue by cacy17** [caligari87/ObAddon#40]
Add the chainsaw into weapons that can spawn.

**Comment by Armaetus** [comment]
It already shows up sometimes in maps..

**Comment by cacy17** [comment]
I figured that out. But it would be nice if you could custamize the spawn rate

**Comment by Armaetus** [comment]
Open up pickups.lua (inside games\doom) and look for the "saw" entry, you can increase the spawn rate of the chainsaw via secrets this way. I think the whole reasoning is to not see it so often after the player picks it up in subsequent maps.
