### ISSUE TITLE
(Suggestion) Random Sector coloring

### ISSUE THREAD

**Issue by nuclear-nomad** [caligari87/ObAddon#41]
As stated in the subject, I think it would be a nice atmospheric addon to be able to allow randomly generated sector coloring that is based off of skybox color and/or fog.

**Comment by Epictyphlosion** [comment]
Could be possible, I know some of the ceiling lights have code for light color. My only fear is that every map would end up looking like a giant, demon-infested disco, lol

**Comment by Kokokokoka** [comment]
>every map would end up looking like a giant, demon-infested disco

sounds like a plan
also, this kinda reminds me of doom64

**Comment by Armaetus** [comment]
I think this has been added with the addition of dynamic lighting used under the GZDoom section module? Please reopen if this is still relevant.
