### ISSUE TITLE
Tnt

### ISSUE THREAD

**Issue by cacy17** [caligari87/ObAddon#42]
When generating a tnt level. Have textures from tnt used. Same with plutonia

**Comment by Armaetus** [comment]
The "Armaetus Texture Pack" uses a good number of Plutonia textures, plus a number of Evilution/TNT textures in it. If there's anything else usable, I could take another look and take another look in the TNT WAD again to check for anything usable.

**Comment by Armaetus** [comment]
I made last sweep and added whatever I can to the texture pack.
