### ISSUE TITLE
Crashes when generating a map

### ISSUE THREAD

**Issue by cacy17** [caligari87/ObAddon#50]
Something related to beams

**Comment by caligari87** [comment]
Please upload the `LOGS.txt` that is generated when the crash happens, otherwise this is impossible to troubleshoot.

**Comment by cacy17** [comment]
It happens when I try to generate on a limit removing engine.

**Comment by Armaetus** [comment]
I am guessing this is when under Doom/Ultimate Doom?

**Comment by Armaetus** [comment]
If this is related to beams, then this has already been fixed by now if you pull the latest files from the green button on the main Github page.
