### ISSUE TITLE
Procedural Gotchas don't work

### ISSUE THREAD

**Issue by pkmnfrk** [caligari87/ObAddon#66]
I've tried various settings/combinations to get Procedural Gotchas to generate, but they do not. Here's some logs, in case they're useful:

https://gist.github.com/pkmnfrk/4d5276c55e13c5ca53288731ea09ee05

I've tried Doom and Doom II, Procedural Gotchas = Everything or 10%, no matter what it's always normal levels.

**Comment by GTD-Carthage** [comment]
Your logs indicate that numerous levels have been succesfully built as procedural gotchas - procedural gotchas are two rooms maps with the non-starter room being a large single arena with a randomized layout. Are you perhaps expecting something more specific?

**Comment by pkmnfrk** [comment]
Hm. You're saying that MAP08 in the log is a gotcha? Interesting. I guess I was expecting something more distinct. That map does not register as "two rooms" to me, but looking at the map in the log, it seems my definition of room is very different from Oblige's! I was expecting hordes of monsters in a big arena-ish level. But in retrospect, I guess that doesn't make sense.

Anyway, thanks for clarifying!

**Comment by GTD-Carthage** [comment]
There is a bug where teleporter escapes can split the arena room into two, so you may occasionally get gotcha's with up to three rooms. I will look into this soon.
