### ISSUE TITLE
Suggestion: MAPINFO automatically saves information of all custom actors

### ISSUE THREAD

**Issue by Frozsoul2019** [caligari87/ObAddon#68]
Currently, when you generate an Oblige WAD that includes any custom actors (e.g. new defined monsters as per http://oblige.sourceforge.net/wiki/?n=Main.NewMons) the WAD will only include the new spawned things on the maps - there is no information in the WAD about what exactly those custom things are supposed to be.  As those things would be defined in the accompanying gameplay mod, this is not an issue in the short-term, but if you choose to revisit the generated map at a future point, you may not remember what mod the map was meant to be played with, or the mod may have changed the spawn id numbers associated with the actors since the map was generated, which would then result in numerous exclamation errors that would be difficult to resolve.

Proposal is to include information about all custom actors in the generated map based on their included information.  One way this could be accomplished is by including a commented-out DoomedNums section of the MAPINFO lump
(reference: https://zdoom.org/wiki/MAPINFO/Editor_number_definition) which lists all of the custom actors used to generate the WAD.

Example in MAPINFO:

/*
DoomedNums
{
   3100 = <Custom Monster 1>
   3102 = <Custom Monster 2>
   ...
   3113 = <Custom Weapon 1>
   ...
} 
*/

**Comment by GTD-Carthage** [comment]
Closing this now - I believe we now have a form of this with the script manager and the fauna module now?
