### ISSUE TITLE
Unpassable map generated by build 2020-02-21

### ISSUE THREAD

**Issue by Keyholder** [caligari87/ObAddon#71]
[unpassable.zip](https://github.com/caligari87/ObAddon/files/4271959/unpassable.zip)

MAP02 extracted form bigger wad attached.

Looks like like a problem in fleshy tunnel leading to yellow door. It seems that it should have T-crossing, but solid wall blocks it.

**Comment by GTD-Carthage** [comment]
Hello, pressing +USE on the small eye that appears between the colored skulls should do the trick - if in case, I'll see if there's a way to make this switch more evident

**Comment by Keyholder** [comment]
Heh! Actually, my problem was not about finding a button for yellow door - it is pretty evident. I haven't been able to get the key at all, because it didn't come on my mind, that I can dive into water to get around that big lump of flesh in front of yellow door :-) Underwater swimming is not among my doomer reflexes, you, clever bastards!

Thank you for best coffee-time fun around, by the way. Your stuff + bleeding edge project brutality is more addictive then meth.

**Comment by GTD-Carthage** [comment]
Thank you - ObAddon is the work a huge team of contributors and we're all having our inputs to make this thing come together. We're glad you're liking what we've got!
