### ISSUE TITLE
GZDoom Boss Generator breaks MAPINFO

### ISSUE THREAD

**Issue by Keyholder** [caligari87/ObAddon#72]
OK, looks like this time I brought you a real bug - see [attached file](https://github.com/caligari87/ObAddon/files/4287141/bad_mapinfo.zip). When I try to create boss level with build 2020-03-02, wad is created with following gameinfo entry in MAPINFO:

```
gameinfo
{
addeventhandlers = "BossGenerator_Handler", 

}
```

Naturally, gzDoom do not accept such syntax.

**Comment by GTD-Carthage** [comment]
I did some changes to the way eventhandlers are added into MAPINFO recently so I'll look into this.

**Comment by GTD-Carthage** [comment]
There should a be a new fix on cutting edge that tries to resolve this issue - please let me know if that comma still appears!

**Comment by Keyholder** [comment]
Seems to work for me now. Thank you!
