### ISSUE TITLE
Script Error: No matching prefab for: fence

### ISSUE THREAD

**Issue by SilverSpireZ** [caligari87/ObAddon#76]
Whenever I try to create a new level pack, I end up getting this error: "Script Error: No matching prefabs for: fence. Anything I'm doing wrong?

[settings.txt](https://github.com/caligari87/ObAddon/files/4611445/settings.txt)

**Comment by GTD-Carthage** [comment]
This issue should be resolved in the cutting edge build - instructions for it are on the main page. Thank you!
