### ISSUE TITLE
Un-passable windows are not blocking projectiles or line of sight

### ISSUE THREAD

**Issue by 0li0li** [caligari87/ObAddon#83]
First, LOVE Obaddon. It's better than Doom 2016 and Eternal. Incredible tool!

I'm not sure if it's on purpose or not, or if there is a command or addon for this, but windows (passable or not) do NOT prevent enemies and the slayer from shooting through windows, fences and other such openings. This leads often to me clearing rooms before even finding the door/keys AND enemies gathering in one spot, so there is both a super dangerous dense chunk of projectiles coming at me, and they are all bunched-up ready to die to a few easy rockets from the outside.

Might have something to do with this: **https://zdoom.org/wiki/Line_SetBlocking**

- BLOCKF_PROJECTILES (16): Blocks projectiles
- BLOCKF_SIGHT (256): Blocks monster line of sight
- etc.

Is there a way for you to fix this, or add a few options along with the Passable Windows field? Otherwise, any idea is a command or mod that take care of that?

**Comment by caligari87** [comment]
Windows and fences have always been shoot-through and see-through all the way back to the first levels of classic Doom.

Fences in particular are used for monster cages as well as player blocking, so it's not as simple as just making all fence midtextures blocking. Perhaps @GTD-Carthage has an easy way to optionally set window lines to get "unshootable glass" textures or something, so I'll let him address that.

Really though I don't see any reason for this to change. It's just part of how Doom levels are made.  You can generate levels with fewer windows if it's that much of a problem.

**Comment by GTD-Carthage** [comment]
I am closing this issue for now as I also have answered this in the Discord - for the heck of it, there are new fabs that have projectile blocking through the use 3D sectors but still allow monster sight.

**Comment by 0li0li** [comment]
By all means, close it, it's fine. I understand it's not a bug. Thank you guys so much for the feedback and amazing project.

Keep it up!
