### ISSUE TITLE
Unknown textures "MIDVINE1" and "G13"

### ISSUE THREAD

**Issue by mridlen** [caligari87/ObAddon#84]
Using Doom2.wad for my iwad

**Comment by GTD-Carthage** [comment]
It's preferable to post LOGS for situations like this but take note unknown material warnings in the log itself are usually safe - if you find any specific prefabs or spots in the map that have missing textures though, a screenshot at the minimum should be sufficient to see what's going on. I will be closing this issue for now but just in case, G13 and MIDVINE1 are textures from the Epic Textures module.
