### ISSUE TITLE
[Linux] [Suggestion] Provide zero compression .pk3 for Linux users

### ISSUE THREAD

**Issue by celestialnavigation** [caligari87/ObAddon#87]
I'm getting the same error as https://github.com/caligari87/ObAddon/issues/7 

>ObFab-Prefabs-7.70.pk3: Script Error: wadfab_load: failed to load VERTEXES lump

I've solved it by following the suggestion of @andwj himself, the creator of Oblige, in that same thread

>BTW, a workaround for the bug is to create the PK3 with no compression on any files (or no compression on the wad files). Naturally that is not great as it makes the PK3 about twice as big, but would allow it to work with stock Oblige 7.70.

But it was a pain and I had to use the command line, I'll have to do it again for every release, and new users might not be able to solve it themselves. Despite the issue being closed the problem persists (and it's likely to be on Oblige's side, not ObAddon, and Oblige is not being maintained anymore). My idea is just providing a separate uncompressed .pk3 for Linux users (it's 35.8 MB instead of 18.1 MB).

**Comment by caligari87** [comment]
Can you try this file and see if it works? (Unfortunately I've already revamped my Oblige setup to use the fixed executable and reverting would be a bit of a pain)

[obaddon.pk3 [Google Drive]](https://drive.google.com/file/d/1IDFHZi3z0TF6y69_Kc5e68qippOUtIqe/view?usp=sharing)

I changed the `makefile` script I use to build ObAddon on Linux, to use zero compression. If this file works for you, then I'll push the change (for anyone using `make` to build) and try to ensure we use these zero-compression archives for future releases.

**Comment by celestialnavigation** [comment]
Thanks for the attention! I had to rename the .zip to .pk3 for Oblige to recognize the addon but after that everything worked with zero errors for multiple test megawads generated.

**Comment by GTD-Carthage** [comment]
I would also like to add a reminder that ObFab is, for practical purposes, an ancient and unsupported predecessor to ObAddon - don't load it with modern ObAddon builds!

**Comment by celestialnavigation** [comment]
> I would also like to add a reminder that ObFab is, for practical purposes, an ancient and unsupported predecessor to ObAddon - don't load it with modern ObAddon builds!

Do you mean as a separate addon? I was only quoting #7 but I'm not loading anything other than ObAddon. The error text I get is only "Script Error: wadfab_load: failed to load VERTEXES lump" even with default ObAddon settings. Very sorry if I caused any confusion.
