### ISSUE TITLE
Suggestion: add monster strength between Feirce (2.5) and CRAZY (12)

### ISSUE THREAD

**Issue by mridlen** [caligari87/ObAddon#90]
Seems like a big jump in difficulty

**Comment by Scionox** [comment]
I have looked and those numbers mean waaaay different things than what you would expect, not sure numbers between Fierce and crazy would even have any significant effect

**Comment by GTD-Carthage** [comment]
I should probably just remove the (12) there and properly communicate that it's basically the setting that ignores monster strength and just adds everything into the basket without regard.
