### ISSUE TITLE
Option to disable mirror generation

### ISSUE THREAD

**Issue by Gar92** [caligari87/ObAddon#96]
Reason: Mobile devices can't handle it

**Comment by GTD-Carthage** [comment]
The ZDoom-ish console command `r_mirror_recursions` can help reduce the amount of repeating mirrored objects in mirrors. Setting this to 0 also gives the mirrors a blank but decent environment map effect as opposed to disabling them entirely through `r_draw_mirrors`.

**Comment by Gar92** [comment]
Thanks, i will try that
